

const quotes = [

    { cn: "即使希望很渺茫，也要鼓起勇气继续前进。", source: "火影忍者", en: "Even if hope is faint, you must muster the courage to move forward. - Naruto" },
    { cn: "没有你，我的人生毫无意义。", source: "四月是你的谎言", en: "Without you, my life has no meaning. - Your Lie in April" },
    { cn: "不论何时，都不要失去希望。", source: "进击的巨人", en: "Never lose hope, no matter what. - Attack on Titan" },
    { cn: "每个人都有自己的战斗方式。", source: "刀剑神域", en: "Everyone has their own way of fighting. - Sword Art Online" },
    { cn: "梦想不会背叛你，只要你不放弃。", source: "灌篮高手", en: "Dreams will not betray you as long as you don't give up. - Slam Dunk" },
    { cn: "世界这么大，人生这么长，总会有这么一个人，让你想要温柔地对待。", source: "哈尔的移动城堡", en: "The world is so big, and life is so long. There will always be someone who makes you want to treat them gently. - Howl's Moving Castle" },
    { cn: "生活坏到一定程度就会好起来，因为它无法更坏。努力过后，才知道许多事情，坚持坚持，就过来了。", source: "龙猫", en: "When life is bad to a certain extent, it will get better because it can't get any worse. After working hard, you will know that many things can be overcome if you persist. - My Neighbor Totoro" },
    { cn: "带上信仰去寻找属于你自己的国度吧！哪怕倾尽一生。", source: "风之谷", en: "Take your faith and seek your own kingdom! Even if it takes a lifetime. - Nausicaä of the Valley of the Wind" },
    { cn: "只有一个人在旅行时，才听得到自己的声音，它会告诉你，这世界比想象中的宽阔。", source: "魔女宅急便", en: "Only when traveling alone can you hear your own voice. It will tell you that the world is wider than you imagine. - Kiki's Delivery Service" },
    { cn: "纵有疾风起，人生不言弃。", source: "起风了", en: "Though the wind may blow, life never gives up. - The Wind Rises" },
    { cn: "不管你曾经被伤害得有多深，总会有一个人的出现，让你原谅之前生活对你所有的刁难。", source: "幽灵公主", en: "No matter how deeply you've been hurt, someone will always come along who makes you forgive all the hardships life has inflicted on you. - Princess Mononoke" },
    { cn: "不管前方的路有多苦，只要走的方向正确，不管多么崎岖不平，都比站在原地更接近幸福。", source: "千与千寻", en: "No matter how difficult the road ahead is, as long as you are going in the right direction, no matter how rough it is, you are closer to happiness than standing still. - Spirited Away" },
    { cn: "爱，不是寻找一个完美的人，而是学会用完美的眼光，欣赏那个并不完美的人。因为爱你，只要你一个肯定，我就足够勇敢。", source: "哈尔的移动城堡", en: "Love is not about finding a perfect person but learning to see an imperfect person perfectly. Because I love you, just your affirmation is enough to make me brave. - Howl's Moving Castle" },
    { cn: "成长，是每个孩子的权力，也是他们必经的征程，或平坦，或崎岖，有悲欢，有离合。", source: "悬崖上的金鱼姬", en: "Growing up is every child's right and their inevitable journey. It can be smooth or rough, with joys and sorrows, separations and reunions. - Ponyo" },
    { cn: "幸福是靠自己争取的，或许这个过程会很艰辛很艰难，但总比站在原地等待要好。", source: "魔女宅急便", en: "Happiness is achieved by oneself. The process may be difficult and arduous, but it's better than standing still and waiting. - Kiki's Delivery Service" },
{ cn: "人生就是一列开往坟墓的列车，路途上会有很多站，很难有人可以自始至终陪着走完。当陪你的人要下车时，即使不舍，也该心存感激，然后挥手道别。", source: "千与千寻", en: "Life is a train heading to the grave. There are many stops along the way. It's hard for anyone to accompany you from beginning to end. When someone who has been with you has to get off, even if you're reluctant, you should be grateful and wave goodbye. - Spirited Away" },
{ cn: "人永远不知道，谁哪次不经意的跟你说了再见之后，就真的不会再见了。", source: "千与千寻", en: "You never know, the last time someone unintentionally says goodbye, it might be the last time you see them. - Spirited Away" },
{ cn: "在茫茫人海中相遇相知相守，无论谁都不会一帆风顺。只有一颗舍得付出，懂得感恩的心，才能拥有一生的爱和幸福。", source: "哈尔的移动城堡", en: "In the vast sea of people, meeting, knowing, and keeping each other is never smooth sailing. Only a heart willing to give and grateful can have a lifetime of love and happiness. - Howl's Moving Castle" },
{ cn: "什么时候我们开始无法像孩子一样，肆意地大呼小叫了。心里的小情绪堆积得像山一样高，直到溢出来。与其如此不如永远像孩子一样。", source: "龙猫", en: "When did we start being unable to shout like children? Our little emotions pile up like mountains until they overflow. Instead of that, why not always be like a child? - My Neighbor Totoro" },
{ cn: "生命可以随心所欲，但不能随波逐流。", source: "猫的报恩", en: "Life can be whatever you want, but you can't go with the flow. - The Cat Returns" },
{ cn: "我不知道离别的滋味是这样凄凉，我不知道说声再见要这么坚强。", source: "千与千寻", en: "I didn't know that parting was so sad, and I didn't know that saying goodbye had to be so strong. - Spirited Away" },
{ cn: "我不知道将去何方，但我已在路上。", source: "千与千寻", en: "I don't know where I'm going, but I'm on my way. - Spirited Away" },
{ cn: "真正重要的东西，总是没有的人比拥有的人清楚。", source: "银魂", en: "The truly important things are always clearer to those who don't have them than to those who do. - Gintama" },
{ cn: "人不是什么时候都能活的光明正大。本想抬头挺胸前进，却不知何时就会沾一身泥巴。不过，即使那样也能坚持走下去的话，总有一天泥巴会干燥掉落的。", source: "银魂", en: "People can't always live with dignity. You want to walk proudly, but sometimes you end up covered in mud. However, if you keep going, the mud will dry and fall off someday. - Gintama" },
{ cn: "拥有和舍弃都很痛苦，既然无论怎样都会痛苦的话，我宁可选择守护它而痛苦。", source: "银魂", en: "Both having and giving up are painful. Since it's painful either way, I'd rather choose to protect it and endure the pain. - Gintama" },
{ cn: "人就是要以自卑为跳板才能跳得更高。", source: "银魂", en: "People need to use their inferiority as a springboard to jump higher. - Gintama" },
{ cn: "人啊，根据重新振作的方法可分为两种：一种是看着比自己卑微的东西，寻找垫底的聊以自慰；另一种则是看着比自己伟大的东西，狠狠踢醒毫无气度的自己。", source: "银魂", en: "People can be divided into two types based on how they recover: those who look at things more pathetic than themselves to find solace, and those who look at things greater than themselves to wake up their own lack of dignity. - Gintama" },
{ cn: "朋友不是说今天开始做的，老板，是在不知不觉中形成的。", source: "银魂", en: "Friends aren't made by saying 'let's be friends' today. They form unconsciously. - Gintama" },
{ cn: "朋友哭泣的时候只要陪着一起哭就好了。朋友苦恼的时候只要抱着脑袋一起苦恼就好。真的是朋友的话就要能分担任何痛苦。当朋友走上歧途的时候，哪怕要损失掉这段友谊也在所不惜，一定要拉他回来。这才是真正武士奉行的友情。", source: "银魂", en: "When a friend cries, just cry with them. When a friend is troubled, just share their troubles. If you are truly friends, you must share any pain. When a friend goes astray, you must pull them back even at the cost of your friendship. That is the true friendship of a samurai. - Gintama" },
{ cn: "无论什么地方、什么处境都有太阳哦，虽然常常会有被云挡住的时候，即使这样只要依然仰望着天空，一定会有从云的缝隙中露出来的时候。所以我们为了不错过那一刻，不可以停止仰望天空，挺直腰杆，径直的仰望着太阳，活下去……", source: "银魂", en: "No matter where or what situation, there is always the sun. Even though it is often blocked by clouds, as long as we continue to look up at the sky, there will always be a moment when it appears through the gaps in the clouds. So, to not miss that moment, we must keep looking up at the sky, stand tall, and look straight at the sun to live... - Gintama" },
{ cn: "正是因为我是一个贪图享乐的人，才更明白人生中有些珍贵的瞬间是不能错过的。", source: "银魂", en: "It's because I'm a hedonist that I understand some precious moments in life shouldn't be missed. - Gintama" },
{ cn: "交朋友就要交那种变成老头还能互相称呼绰号的。", source: "银魂", en: "When making friends, choose those you can still call by nicknames when you're old. - Gintama" },
{ cn: "人不管长多大，都仍然在寻觅容身之所的旅程上前行。", source: "银魂", en: "No matter how old people get, they are still on a journey seeking a place to belong. - Gintama" },
{ cn: "暴走族算什么？我可是在人生的路上暴走的呢！", source: "银魂", en: "What are biker gangs? I'm running wild on the road of life! - Gintama" },
{ cn: "活着并不是那么光荣的事，真正的光荣是你就算丢脸也要忍傉偷生地活着。", source: "银魂", en: "Living isn't such an honorable thing. True honor is surviving even if it means enduring shame. - Gintama" },
{ cn: "武士做的事，是不需要什么大道理的，只要那里有你想要保护的东西，那就拔剑好了！", source: "银魂", en: "What a samurai does doesn't need any grand reason. As long as there's something you want to protect, just draw your sword! - Gintama" },
{ cn: "人啊，只有在集体中寻找自我，才有真正活着的感觉。", source: "银魂", en: "People can only truly feel alive by finding themselves within a group. - Gintama" },
{ cn: "关于自己的生活，我和你都不是读者，而是作者。至少结局，还是能自己说了算的。", source: "银魂", en: "When it comes to our own lives, we're not readers, we're authors. At least we can decide the ending ourselves. - Gintama" },
{ cn: "即便如此，还是想保护这个世界。", source: "银魂", en: "Even so, I still want to protect this world. - Gintama" },
{ cn: "与其想着怎样华丽地死去，不如想想怎样华丽地活下去吧！", source: "银魂", en: "Instead of thinking about how to die gloriously, think about how to live gloriously! - Gintama" },
{ cn: "其实人长大真的是简单的超出想象，但凡事都抱着一颗童心去快乐享受却反而很难。", source: "银魂", en: "Growing up is easier than you think, but enjoying everything with a child's heart is much harder. - Gintama" },
{ cn: "没有一定会输的比赛，除非放弃。", source: "排球少年", en: "There's no such thing as a definite loss in a match, unless you give up. - Haikyuu!!" },
{ cn: "即使没有必胜的信心，即便被周围人说不可能，只有我们自己不能说出这种话。", source: "排球少年", en: "Even if we don't have the confidence to win, even if others say it's impossible, we must never say it ourselves. - Haikyuu!!" },
{ cn: "为了可以真正享受输赢，需要有强大的实力。", source: "排球少年", en: "To truly enjoy winning and losing, one must have strong abilities. - Haikyuu!!" },
{ cn: "正因为没有翅膀，所以人们才会寻找飞翔的翅膀。", source: "排球少年", en: "It is precisely because we lack wings that we seek them to fly. - Haikyuu!!" },
{ cn: "我的确很矮，但是我会靠着双脚飞跃过任何墙壁。", source: "排球少年", en: "I may be short, but I can jump over any wall with my own feet. - Haikyuu!!" },
{ cn: "机会，只会眷顾那些有准备的人！", source: "排球少年", en: "Opportunity only favors those who are prepared! - Haikyuu!!" },
{ cn: "好不容易站到这个场地上来了，怎么能轻易就结束呢？", source: "排球少年", en: "After all the effort to get here, how could we end it easily? - Haikyuu!!" },
{ cn: "如果只往高处看到话，在不经意间就会被别人超过。", source: "排球少年", en: "If you only look upwards, you may be overtaken by others without noticing. - Haikyuu!!" },
{ cn: "明明可以有更多选择，怎么可能不去做啊。", source: "排球少年", en: "When there are so many choices available, how can we not pursue them? - Haikyuu!!" },
{ cn: "无论战况再不利，继续战斗的理由只有一个，因为，还没有输。", source: "排球少年", en: "No matter how unfavorable the battle, the reason to continue fighting is one - because it's not over yet. - Haikyuu!!" },
{ cn: "别人怎么看待你什么的又有什么关系！只要自己觉得自己很帅气就好了！", source: "排球少年", en: "What does it matter how others see you? As long as you think you are cool, that's enough! - Haikyuu!!" },
{ cn: "不管对手是强是弱，结果只有胜负两种。输了的话，就无法站在球场上了。", source: "排球少年", en: "No matter if the opponent is strong or weak, there are only two outcomes: win or lose. If you lose, you can't stand on the court. - Haikyuu!!" },
{ cn: "就算对手是完全无法触及的强敌也好，失去斗志的话，就无法取胜了啊。", source: "排球少年", en: "Even if the opponent is an unreachable strong foe, if you lose your fighting spirit, you cannot win. - Haikyuu!!" },
{ cn: "没有什么事情是在开始之前就喜欢了的不是吗？开始做一件事情并不需要有“坚定不移的意志”或“崇高的动机”之类的，顺势也会变得格外重要呢。开始做一件事情需要的只是一点点的好奇心而已哦。", source: "排球少年", en: "Isn't it true that you don't like something before you start? To begin, you don't need 'unwavering will' or 'noble motives'; sometimes just going with the flow becomes especially important. All you really need to start is a bit of curiosity. - Haikyuu!!" },
{ cn: "飞雄的天才之处，与其说是技术多好，不如说多半是他那股一根筋的傻劲吧。正常人都会犹豫不决的时候，他却能勇往直前。", source: "排球少年", en: "Hinata's genius lies not so much in his skills as in his sheer stubbornness. Where most would hesitate, he charges ahead. - Haikyuu!!" },
{ cn: "优越的体格，出众的体能，他拥有的武器与这些都不一样，'好痛苦，想停止脚步'在这么想的那一瞬间向前跃步。", source: "排球少年", en: "Beyond a superior physique and outstanding physical abilities, his true strength lies elsewhere. 'It hurts, I want to stop,' he thinks, and in that moment, he leaps forward. - Haikyuu!!" },
{ cn: "听好了，所谓的排球，是在网这边的全员都是伙伴啊！", source: "排球少年", en: "Listen up, in volleyball, everyone on this side of the net is a teammate! - Haikyuu!!" },
{ cn: "可是呢，平凡的我啊，哪有时间低头，回望啊。", source: "排球少年", en: "But me, being ordinary, I have no time to bow down or look back. - Haikyuu!!" },
{ cn: "飞吧。", source: "排球少年", en: "Fly. - Haikyuu!!" },
{ cn: "想要维持强者的身份，就要无数次抛弃过往的强大。", source: "排球少年", en: "To maintain the status of the strong, you must repeatedly abandon your past strengths. - Haikyuu!!" },
{ cn: "努力能让才华开花。", source: "排球少年", en: "Effort allows talent to bloom. - Haikyuu!!" },
{ cn: "得知自己很弱小后，接受眼前的现实，用尽全力去打磨每一件自己能用得上的武器。", source: "排球少年", en: "After realizing your own weakness, accept the present reality and put all your effort into refining every tool at your disposal. - Haikyuu!!" },
{ cn: "人之一生，因梦想与感动而精彩。", source: "排球少年", en: "A life becomes brilliant through dreams and emotions. - Haikyuu!!" },
{ cn: "不要低下你们的头，排球可是一项，需要始终向上看的运动啊！！", source: "排球少年", en: "Don't lower your heads; volleyball is a sport that always requires you to look up!! - Haikyuu!!" },
{ cn: "人与人的相遇，是会催生化学反应的。说不定就在这个瞬间，某处发生的能改变世界的相遇。", source: "排球少年", en: "Encounters between people can catalyze chemical reactions, and perhaps at this very moment, somewhere, an encounter is happening that could change the world. - Haikyuu!!" },
{ cn: "求神也不一定能赢得比赛啊。", source: "排球少年", en: "Praying to God doesn't necessarily win you the game. - Haikyuu!!" },
{ cn: "好痛苦，想停止脚步，在这么想的那一瞬，向前跃步。偶尔会有这么一个球，让人光是想想就能振奋精神，重拾信心。就像在攀登高耸险峰的途中忽然出现一颗楔钉，这不是什么奇迹，也是通过不断努力才能抓住的一颗楔钉，抓住这些来之不易的一颗楔钉，继续向着更高处前进。", source: "排球少年", en: "The pain makes you want to stop, but in that moment of thought, you leap forward. Sometimes, there's a play that alone can invigorate your spirit and restore your confidence, like a piton suddenly appearing on a steep climb—not a miracle, but a result of relentless effort, a hard-won piton that lets you continue climbing higher. - Haikyuu!!" },
{ cn: "明明可以变得更强却不去努力，那样的人生多无趣。", source: "排球少年", en: "A life where one could become stronger but chooses not to strive is utterly dull. - Haikyuu!!" },
{ cn: "对我来说，不管是怎样的托球，都是值得珍惜的，不管什么位置我都会跳上去，不管怎样的球我都会扣下去。所以，把球托给我！", source: "排球少年", en: "To me, every set is precious; no matter the position, I'll jump for it, no matter the type of pass, I'll spike it. So, pass me the ball! - Haikyuu!!" },
{ cn: "比赛确实是输了，不过难道不是一场有收获的比赛吗？'败北'是弱小的证据吗？对于你们来说'败北'不应该是考验吗。看你们拜倒在地之后是否还能重新站起来继续前行，如果你们一直跪在那里不起来那才证明了你们的弱小。", source: "排球少年", en: "Yes, we lost the match, but wasn't it a match with gains? Is 'defeat' a sign of weakness? Shouldn't 'defeat' be a test for you? It's whether you can stand up and keep moving forward after being knocked down that counts; staying down is what really proves weakness. - Haikyuu!!" },
{ cn: "既然我的身高不如高个子选手，那就争那一秒，更快抵达顶端的那一厘米、一毫米。", source: "排球少年", en: "Since I'm not as tall as the taller players, I'll compete for that second, to reach the top a centimeter, a millimeter quicker. - Haikyuu!!" },
{ cn: "世界啊，为我加油助威吧！", source: "排球少年", en: "World, cheer for me! - Haikyuu!!" },
{ cn: "坚信「自己的实力绝非仅此而已」,并沿着这条路一直走下去,相较于哀叹一声「我可比不上那些天才」,然后放弃,可是要艰辛得多哦。", source: "排球少年", en: "Believe that 'my abilities go beyond this,' and keep going down this path; it's much tougher than simply sighing 'I can't match those geniuses' and giving up. - Haikyuu!!" },
{ cn: "坚硬的地板，助我一飞冲天吧！", source: "排球少年", en: "Hard floor, help me soar to the skies! - Haikyuu!!" },
{ cn: "光芒越强，影子就越浓，从而更加衬托出光芒的耀眼！", source: "黑子的篮球", en: "The brighter the light, the deeper the shadow, accentuating the brilliance even more! - Kuroko's Basketball" },
{ cn: "尽人事,以待天命。", source: "黑子的篮球", en: "Do your best and leave the rest to fate. - Kuroko's Basketball" },
{ cn: "以过去的结果推论得出的就只有预想，没比赛过是不会知道胜负的。", source: "黑子的篮球", en: "Outcomes based on past results are merely predictions; you won't know the winner until the game is played. - Kuroko's Basketball" },
{ cn: "只有在放弃的时候，可能性才会变为零，无论别人觉得多么没有意义，我不想让自己认为可能性为零，所以……我绝对不会放弃！", source: "黑子的篮球", en: "Possibility only becomes zero when you give up. No matter how meaningless others may find it, I refuse to see it as zero, so... I will absolutely never give up! - Kuroko's Basketball" },
{ cn: "一旦放弃，比赛就会在那一刻结束。", source: "灌篮高手", en: "The moment you give up, that's when the game ends. - Slam Dunk" },
{ cn: "天才的字典里，没有不可能这三个字。", source: "灌篮高手", en: "The word 'impossible' doesn't exist in a genius's dictionary. - Slam Dunk" },
{ cn: "人们总是追求表面答案，结果错失无可取代的宝物。", source: "灌篮高手", en: "People often chase after superficial answers and end up missing irreplaceable treasures. - Slam Dunk" },

{ cn: "成长，是每个孩子的权力，也是他们必经的征程，或平坦、或崎岖，有悲欢，有离合。", source: "悬崖上的金鱼姬", en: "Growing up is every child's right and their inevitable journey, marked by both smooth and rough paths, joys, and separations. - Ponyo" },
{ cn: "重要的东西全部都在半径3米之内。", source: "悬崖上的金鱼姬", en: "All that is important lies within a radius of three meters. - Ponyo" },
{ cn: "每天早上睁开眼睛，看到你和阳光都在，这就是我想要的未来。", source: "悬崖上的金鱼姬", en: "Opening my eyes every morning to see both you and the sunshine is the future I desire. - Ponyo" },
{ cn: "拥抱的时候，是人和人，心脏依靠最近的时候，近到能听见彼此的心跳。", source: "悬崖上的金鱼姬", en: "In an embrace, it is the moment when human hearts come closest to each other, close enough to hear each other's heartbeats. - Ponyo" },
{ cn: "信仰到底是什么呢？就是纵身一跃，就是我们跟神之间一个永远的约定，是舍弃旧的去开始新的生活。", source: "悬崖上的金鱼姬", en: "What exactly is faith? It's a leap, an eternal covenant between us and the divine, a commitment to discard the old and start anew. - Ponyo" },
{ cn: "信仰就是从今以后，再也不要放开你的手。", source: "悬崖上的金鱼姬", en: "Faith means, from now on, never letting go of your hand. - Ponyo" },
{ cn: "我不知道为什么自己会爱上你，但是你就是我没有爱上别人的理由。", source: "虞美人盛开的山坡", en: "I don't know why I fell in love with you, but you are the reason I haven't fallen for anyone else. - The Beauty's Grave" },
{ cn: "人总是活在矛盾当中，对人类的绝望以及信赖，我们在这夹缝间求生存。", source: "虞美人盛开的山坡", en: "Humans always live amidst contradictions, torn between despair and trust in humanity, seeking to survive in these cracks. - The Beauty's Grave" },
{ cn: "或许前路永夜，即便如此我也要前进，因为星光即使微弱也会为我照亮前途。", source: "四月是你的谎言", en: "Even if the path ahead is eternally night, I must still advance, for even the faintest starlight will illuminate my way. - Your Lie in April" },
{ cn: "你的所言所行，全都闪烁着光芒，太过刺目，于是我闭上双眼，但内心还是无法停止对你的憧憬。", source: "四月是你的谎言", en: "Everything you say and do shines brightly, so dazzling that I must close my eyes, yet I cannot stop longing for you in my heart. - Your Lie in April" },
{ cn: "每当心情郁闷的时候，用手托腮就好，手臂会因为帮上忙而开心的。", source: "四月是你的谎言", en: "Whenever you feel gloomy, just prop your cheek with your hand; your arm will be happy to assist. - Your Lie in April" },
{ cn: "和他相遇的瞬间，我的人生就改变了。所见所闻所感，目之所及全都开始变得多姿多彩起来，全世界，都开始发光发亮！", source: "四月是你的谎言", en: "The instant I met him, my life was transformed. Everything I saw, heard, and felt began to burst with color, and the entire world started to shine! - Your Lie in April" },
{ cn: "干燥的空气，尘埃的味道，我在其中。", source: "四月是你的谎言", en: "The dry air and the taste of dust, I am amidst it. - Your Lie in April" },
{ cn: "烦恼着迷惑着痛苦着，而最后得到的答案却简单到让我不禁想笑出来。", source: "四月是你的谎言", en: "Troubled, confused, and pained, yet the answers I eventually find are so simple that they make me want to laugh. - Your Lie in April" },
{ cn: "看吧，星星只有在夜里才璀璨夺目啊。", source: "四月是你的谎言", en: "See, the stars only truly dazzle during the night. - Your Lie in April" },
{ cn: "我喜欢了你十年，却用整个四月，编织了一个我不爱你的谎言。", source: "四月是你的谎言", en: "I loved you for ten years, yet I spent an entire April weaving a lie that I did not love you. - Your Lie in April" },
{ cn: "在美丽的谎言中，一个走出了深渊，一个走向了天堂。", source: "四月是你的谎言", en: "Within beautiful lies, one walked out of the abyss, and the other ascended to heaven. - Your Lie in April" },
{ cn: "苦恼着，歇斯底里着，痛苦着，不断挣扎的数月时间，这一切会在未来的某一瞬间得到回报。我们或许就是被那个瞬间迷住的，一种无可救药的生物吧。", source: "四月是你的谎言", en: "Months of turmoil, hysteria, and pain, all this struggling will be rewarded in an instant in the future. Perhaps we are creatures hopelessly enchanted by such moments. - Your Lie in April" },
{ cn: "生活坏到一定程度就会好起来，因为它无法更坏。努力过后，才知道许多事情，坚持坚持，就过来了。", source: "龙猫", en: "Life gets better when it can't get any worse. After striving, you realize that many challenges can be overcome by simply persisting. - My Neighbor Totoro" },
{ cn: "有些烦恼，丢掉了，才有云淡风轻的机会。", source: "龙猫", en: "By discarding certain troubles, you open the chance for tranquility. - My Neighbor Totoro" },
{ cn: "这世界上没有毫无理由的横空出世，所谓的运气好，不过是因为他们时刻准备着而已。那些苟且的时光，那些苦痛的日子，他们不是没有经历，而是你不知道。", source: "龙猫", en: "There are no sudden rises without reason; what's called good luck is merely constant readiness. Those times of scraping by, those days of suffering, they were not unseen but merely unknown to you. - My Neighbor Totoro" },
{ cn: "无畏孤单，因为这个世界上，肯定有一个人正努力走向你。", source: "龙猫", en: "Do not fear being alone, for in this world, there is definitely someone striving to reach you. - My Neighbor Totoro" },
{ cn: "什么时候我们开始无法像孩子一样肆意地大呼小叫了？心里的小情绪堆积得像山一样高，直到溢出来。与其如此，不如永远像孩子一样。", source: "龙猫", en: "When did we lose the ability to shout freely like children? Our minor emotions accumulate like mountains until they spill over. Rather than endure that, it's better to remain forever childlike. - My Neighbor Totoro" },
{ cn: "现实是给那些缺乏想象力的人的。", source: "龙猫", en: "Reality is for those who lack imagination. - My Neighbor Totoro" },
{ cn: "人生的某些障碍，你是逃不掉的。与其费尽周折绕过去，不如勇敢的地攀越，或许这会铸就你人生的高点。", source: "龙猫", en: "Some obstacles in life are inescapable. Rather than exhausting yourself trying to avoid them, it's better to courageously surmount them—this may well become the pinnacle of your life. - My Neighbor Totoro" },
    { cn: "生命可以随心所欲，但不能随波逐流。", source: "猫的报恩", en: "Life can be as you wish, but you must not just drift along. - The Cat Returns" },
    { cn: "当一个人用心创造一样东西时，这样东西便有了灵魂。", source: "猫的报恩", en: "When something is created with heart, it gains a soul. - The Cat Returns" },
    
{ cn: "你应该要学着做你自己，面对真实的自我，只要做到这一点，你就什么都不用惧怕。", source: "猫的报恩", en: "You should learn to be yourself and face your true self; by doing so, you'll have nothing to fear. - The Cat Returns" },
    { cn: "你不能等待别人来安排你的人生；自己想要的，自己争取。", source: "猫的报恩", en: "You can't wait for others to arrange your life; you must strive for what you want yourself. - The Cat Returns" },
    { cn: "人是要长大的，有天你也会推着婴儿车幸福地在街上行走，而曾经的喜欢，不管曾经怎样，都会幻化成风，消失在时光的隧道。所以向前走，向前走，无须回头。", source: "猫的报恩", en: "People grow up; one day, you'll happily push a stroller down the street, and all past affections, no matter what they were, will vanish like the wind in the tunnel of time. So, move forward, move forward, with no need to look back. - The Cat Returns" },
    { cn: "我始终相信，在这个世界上，一定有另一个自己，在做着我不敢做的事，在过着我想过的生活。", source: "猫的报恩", en: "I always believe that somewhere in this world, there's another version of me doing the things I'm too afraid to do, living the life I desire. - The Cat Returns" },
   


 { cn: "人生就是一列开往坟墓的列车，路途上会有很多站，很难有人可以自始至终陪着走完。当陪你的人要下车时，即使不舍，也该心存感激，然后挥手道别。", source: "千与千寻", en: "Life is a train heading to the grave with many stops along the way. It's rare for someone to accompany you the whole journey. When it's time for someone to depart, though hard, be grateful and wave goodbye. - Spirited Away" },
    { cn: "人永远不知道，谁哪次不经意的跟你说了再见之后，就真的不会再见了。", source: "千与千寻", en: "You never know when a casual goodbye could be the last. - Spirited Away" },
    { cn: "我不知道将去何方，但我已在路上。", source: "千与千寻", en: "I don't know where I'm going, but I am on my path. - Spirited Away" },
    { cn: "不管前方的路有多苦，只要走的方向正确，不管多么崎岖不平，都比站在原地更接近幸福。", source: "千与千寻", en: "No matter how bitter the road ahead, as long as the direction is right, any ruggedness is closer to happiness than standing still. - Spirited Away" },
    { cn: "我不知道离别的滋味是这样凄凉，我不知道说声再见要这么坚强。", source: "千与千寻", en: "I never knew parting could be so bleak, nor that saying goodbye required such strength. - Spirited Away" },   
    { cn: "我不用再去远方寻找，闪耀珍贵的所有就在身边。", source: "千与千寻", en: "I no longer need to search far; all that is precious and gleaming is right beside me. - Spirited Away" },
    { cn: "只有一个人在旅行时，才听得到自己的声音，它会告诉你，这世界比想象中的宽阔。", source: "千与千寻", en: "Only when traveling alone can you truly hear your own voice, which tells you the world is wider than you imagined. - Spirited Away" },
    { cn: "人们常常会欺骗你，是为了让你明白，有时候，你唯一应该相信的人就是你自己。", source: "千与千寻", en: "People often deceive you to make you realize that sometimes the only person you should trust is yourself. - Spirited Away" },
    { cn: "太多的事，慢慢地就不能做了，太多的人，渐渐地就不见了。成长似乎是一个丢失的过程。", source: "千与千寻", en: "Too many things gradually become undoable, too many people gradually fade away. Growing up seems to be a process of losing. - Spirited Away" },
    { cn: "世界这么大，人生这么长，总会有这么一个人，让你想要温柔的对待。", source: "千与千寻", en: "The world is so vast, life so long, there will always be someone you'll want to treat gently. - Spirited Away" },
    { cn: "有时候，坚持了你最不想干的事情之后，便可得到你最想要的东西。", source: "天空之城", en: "Sometimes, by persevering through what you least want to do, you may gain what you most desire. - Castle in the Sky" },


    
    { cn: "堕落是不需要理由的 ，但是，不堕落却是有原因的。对处于青春期的人来说，要是没有理由的话，谁都会变得堕落。", source: "《CLANNAD》", en: "Falling is easy and does not require any reason, but staying upright does. For teenagers, without a reason, anyone can fall. - CLANNAD" },
    { cn: "这个世界是美丽的，就算充满了悲伤和泪水，也请你睁开双眼，去做你想做的事，成为你想成为的人，去爱你想爱的人，找你想要的朋友。不必焦躁，不必迷惘，请慢慢地长大，无论发生什么事情，请不要后悔与这个世界相遇。", source: "《CLANNAD》", en: "This world is beautiful, even if filled with sadness and tears. Please open your eyes, do what you want to do, become who you want to be, love who you want to love, and find the friends you want. Don't be anxious or confused, grow up slowly. No matter what happens, don't regret meeting this world. - CLANNAD" },
    { cn: "无知而又纯洁的岁月，是任何人都曾拥有的。", source: "CLANNAD", en: "The ignorant and pure years are something everyone once had. - CLANNAD" },
    { cn: "笑是对身边的事物感到一瞬间的幸福而表现出来的东西。", source: "CLANNAD", en: "A smile is a manifestation of the momentary happiness felt for the things around you. - CLANNAD" },
    { cn: "世界上没有一成不变的事物，所以只要以其他方式找到自己的快乐就行了。", source: "CLANNAD", en: "Nothing in the world is unchanging, so find your happiness in other ways. - CLANNAD" },
    { cn: "听潮鸣潮起潮落，看人生人来人往。", source: "CLANNAD", en: "Listen to the tide rise and fall, watch life come and go. - CLANNAD" },
    { cn: "世界是美丽的，就算充满悲伤和泪水，也请睁开你的双眼，去做你想要做的事情，成为你想要成为的人，不要焦躁，慢慢的去成长。", source: "CLANNAD", en: "The world is beautiful, even if filled with sadness and tears. Please open your eyes, do what you want to do, become who you want to be, don't be anxious, grow up slowly. - CLANNAD" },
    { cn: "别对我这么温柔，我是个笨蛋，你对我温柔的话我会误会的。", source: "CLANNAD", en: "Don't be so kind to me, I'm a fool. If you are kind to me, I will misunderstand. - CLANNAD" },
    { cn: "我也很没用，但是两个人一起的话，就会变得很坚强。", source: "CLANNAD", en: "I'm useless too, but if we are together, we will become strong. - CLANNAD" },
    { cn: "人生即是到来、相遇、陪伴、离开。", source: "CLANNAD", en: "Life is about coming, meeting, accompanying, and leaving. - CLANNAD" },
    { cn: "世界是美丽的，就算同时充斥着悲伤的泪水和奇迹的光辉。所以，也请睁开你的眼睛，去做你想做的事，成为你想成为的人，不要焦躁，慢慢的去成长。到了真正的金秋华年，你会发现自己的选择是这样美好……原来，自己，一直都行走在被光守护的坡道之上。", source: "CLANNAD", en: "The world is beautiful, even if filled with tears of sadness and the brilliance of miracles. So, please open your eyes, do what you want to do, become who you want to be, don't be anxious, grow up slowly. When you reach the golden autumn of life, you will find that your choices were so wonderful... It turns out that you have always been walking on a path protected by light. - CLANNAD" },
    { cn: "探寻真理之人不可心怀傲慢，不可嘲笑无法用科学解释的奇迹，不可回避这个世界的美丽。", source: "CLANNAD", en: "Those who seek the truth should not be arrogant, should not mock miracles that cannot be explained by science, and should not avoid the beauty of this world. - CLANNAD" },
    { cn: "没关系，不要再哭了，我是风，正包围在你的身边。", source: "CLANNAD", en: "It's okay, don't cry anymore, I am the wind, surrounding you. - CLANNAD" },
    { cn: "无论今后遇到什么事情，请不要后悔与我相遇。", source: "CLANNAD", en: "No matter what happens in the future, please don't regret meeting me. - CLANNAD" },
{ cn: "无论栖息于清流还是栖息于泥水，重要的是你怎么游。", source: "暗杀教室", en: "No matter if you live in clear streams or muddy waters, what matters is how you swim. - Assassination Classroom" },
    { cn: "不拼尽全力试试怎么可能知道？", source: "刺客伍六七", en: "How can you know if you don't give it your all? - Scissor Seven" },
    { cn: "你将不再是道具，而是成为人如其名的人。", source: "紫罗兰永恒花园", en: "You will no longer be a tool, but a person who lives up to their name. - Violet Evergarden" },
    { cn: "有些梦想虽然遥不可及，但不是不可能实现。只要我足够的强。", source: "秦时明月", en: "Some dreams are far away, but not impossible to achieve. As long as I am strong enough. - The Legend of Qin" },
    { cn: "不可以逃避！不可以逃避！不可以逃避！- Neon Genesis Evangelion", en: "You must not run away! You must not run away! You must not run away! - Neon Genesis Evangelion" },
    { cn: "幸福，不是长生不老，不是大鱼大肉，不是权倾朝野。幸福是每一个微小的生活愿望达成。当你想吃的时候有得吃，想被爱的时候有人来爱你。", source: "飞屋环游记", en: "Happiness is not about eternal life, great wealth, or power. Happiness is when every small wish in life comes true. When you want to eat, there is food to eat. When you want to be loved, someone loves you. - Up" },
    { cn: "大部分人并不想长大，只是没办法继续当一个小孩子。", source: "小林家的龙女仆", en: "Most people don't want to grow up, they just can't keep being a child. - Miss Kobayashi's Dragon Maid" },
    { cn: "没有未来的未来，根本不是我想要的未来啊！", source: "境界的彼方", en: "A future without a future is not a future I want at all! - Beyond the Boundary" },
    { cn: "就算颠覆整个宇宙，我也要把你找回来。", source: "凉宫春日的消失", en: "Even if I have to overturn the entire universe, I will find you. - The Disappearance of Haruhi Suzumiya" },
    { cn: "承认吧，我们是最弱的种族。正因为我们天生什么都没有，所以才注定要驾驭一切！", source: "游戏人生", en: "Admit it, we are the weakest race. Because we are born with nothing, we are destined to conquer everything! - No Game No Life" },
    { cn: "真正相信奇迹的家伙，本身和奇迹一样了不起啊！", source: "星游记", en: "Those who truly believe in miracles are as extraordinary as the miracles themselves! - Rainbow Sea" },
    { cn: "即使再怎么勉强、再怎么不自量力、再怎么厚颜无耻，也要用自己的双手，保护最珍惜的东西。", source: "魔法禁书录", en: "No matter how much I overexert, how foolish I am, or how shameless I am, I must protect what I cherish with my own hands. - A Certain Magical Index" },
    { cn: "即使痛苦难过的时候，也要全家人一如既往的坐在一起吃饭，因为最糟糕的是饥饿和孤单。", source: "夏日大作战", en: "Even in painful and sad times, the family should always eat together, because the worst things are hunger and loneliness. - Summer Wars" },
    { cn: "即使世界充满污秽与罪恶，也仍值得我们为其而战。", source: "双星之阴阳师", en: "Even if the world is full of filth and evil, it is still worth fighting for. - Twin Star Exorcists" },
    { cn: "最美的不是下雨天，而是与你一起躲过雨的屋檐。", source: "青春之旅", en: "The most beautiful thing is not the rainy day, but the eaves we took shelter under together. - Blue Spring Ride" },
    { cn: "只要努⼒活下去，总有⼀天会笑着回忆。", source: "不可意思游戏", en: "As long as you strive to live, one day you will smile when you look back. - Game of Imagination" },
    { cn: "连接遥远的过去与未来,我们为此⽽存在……", source: "棋魂", en: "Connecting the distant past and future, we exist for this... - Hikaru no Go" },
    { cn: "深藏不露是一种卓越的才能。", source: "欢迎来到实力至上主义教室", en: "Hiding one's abilities is a remarkable talent. - Classroom of the Elite" },
    { cn: "不过只要⾝为⼈类，每个⼈都能体会被神遗弃的感觉。", source: "⼫⿁", en: "As long as one is human, everyone can feel abandoned by God. - Corpse Princess" },
    { cn: "所谓的朋友就是，不管是误⼊歧途还是犯了罪过都要⼀起⾛下去⼀起背负，这才是真正的朋友啊！", source: "男⼦⾼中⽣的⽇常", en: "True friends are those who walk and bear the consequences together, no matter if they go astray or commit mistakes. - Daily Lives of High School Boys" },
    { cn: "虽然我们不可能⼀辈⼦不受伤害，但是我们可以尽最⼤努⼒不去伤害别⼈。", source: "⾎族禁域", en: "Although we can't go through life without being hurt, we can do our best not to hurt others. - Bloodline Domain" },
    { cn: "就算是对我抱有敌意的人，也是被某个人深爱着而降生在这个世界上的。", source: "罪恶王冠", en: "Even those who harbor hostility towards me were born into this world loved by someone. - Guilty Crown" },
    { cn: "这个世界，只需要一把剑就可以去往任何地方。", source: "刀剑神域", en: "In this world, with just one sword, you can go anywhere. - Sword Art Online" },
    { cn: "人类真正的强大是自我改变。", source: "一拳超人", en: "Human's true strength is self-change. - One Punch Man" },
   
    { cn: "即使停下脚步，徘徊不前，时间也不会停止流逝，它才不会驻留在你身旁，陪着你一起呼天抢地。", source: "鬼灭之刃", en: "Even if you stop and hesitate, time will not stop. It won't stay by your side and cry out with you. - Demon Slayer" },
    { cn: "仿佛这世上所有粗鄙之语，都是为了我而被编纂出来一般。", source: "鬼灭之刃", en: "It seems like all the vulgar words in this world were created just for me. - Demon Slayer" },
    { cn: "纵使我身形俱灭，也定将恶鬼斩杀。", source: "鬼灭之刃", en: "Even if my body is destroyed, I will still slay the demons. - Demon Slayer" },
    { cn: "如果能在没有鬼的和平世界里，再次转世为人的话，一定要告诉你，我喜欢你。", source: "鬼灭之刃", en: "If I can be reborn in a peaceful world without demons, I will tell you that I like you. - Demon Slayer" },
    { cn: "不经意间握住的手，是如此强大又温暖。", source: "鬼灭之刃", en: "The hand I unintentionally held was so strong and warm. - Demon Slayer" },
    { cn: "生活虽然不易，但也很幸福，不过人生就像天空一样，有四季更替，时刻都在变化，不会一直晴空万里，也不会一直大雪纷飞。", source: "鬼灭之刃", en: "Life is not easy, but it is also very happy. Life is like the sky, with changing seasons and constant change. It won't always be sunny, nor will it always be snowy. - Demon Slayer" },
    { cn: "若光凭愤怒的感情就能赢的话，这世上早就不再有鬼了吧。", source: "鬼灭之刃", en: "If anger alone could win, there would be no demons left in this world. - Demon Slayer" },
    { cn: "生活虽然并不轻松，但很幸福，但是人生也会阴有晴，会不断变化，不会一直放晴，也不会一直下雪，而幸福被毁坏的时候，总会带有血的味道。", source: "鬼灭之刃", en: "Life is not easy, but it is happy. Life has sunny and cloudy days, it constantly changes. It won't always be sunny, nor will it always snow. When happiness is destroyed, it always carries the scent of blood. - Demon Slayer" },
    { cn: "已经逝去的生命注定不会再归来，活生生的人无法像鬼一样再生，为什么要掠夺，为什么要践踏生命。", source: "鬼灭之刃", en: "A life that is gone will not return. The living cannot be reborn like demons. Why plunder, why trample on life? - Demon Slayer" },
    { cn: "不管多么痛苦，也不要逃往轻松的一边。", source: "鬼灭之刃", en: "No matter how painful it is, don't escape to the easy side. - Demon Slayer" },
    { cn: "你可以逃跑，可以哭泣，但不能放弃。", source: "鬼灭之刃", en: "You can run, you can cry, but you can't give up. - Demon Slayer" },
    { cn: "不论何时，都请自豪地活下去。", source: "鬼灭之刃", en: "Live with pride, no matter what. - Demon Slayer" },
    { cn: "谁都会害怕失去，尤其是拼了命的珍惜后，却还是什么都留不住。", source: "东京喰种", en: "Everyone fears loss, especially after cherishing it with all their might, yet still losing everything. - Tokyo Ghoul" },
    { cn: "这世上所有的不公平都是因为当事人能力的不足。", source: "东京喰种", en: "All the unfairness in this world is due to the incompetence of the person involved. - Tokyo Ghoul" },
    { cn: "真正重要的东西，不管痛苦也好、悲伤也好。都要努力到底，就算失去生命，也要用双手来保护到底。", source: "东京喰种", en: "The truly important things, whether it's pain or sadness. You must strive to the end, even if it costs your life, you must protect them with your own hands. - Tokyo Ghoul" },
    { cn: "世界就在我掌中。", source: "命运石之门", en: "The world is in my hands. - Steins;Gate" },
    { cn: "人们总是会注视着自己所珍视的东西，唯独没有自己。", source: "命运石之门", en: "People always look at what they cherish, but never at themselves. - Steins;Gate" },
    { cn: "人类从根本上说是时间性的存在。", source: "命运石之门", en: "Humans are fundamentally temporal beings. - Steins;Gate" },
    { cn: "过去在远离，未来是否意味着正在靠近。", source: "命运石之门", en: "As the past moves further away, does that mean the future is approaching? - Steins;Gate" },
    { cn: "时间会随着人的感觉而变长或变短，相对论真是既浪漫又伤感的东西呢。", source: "命运石之门", en: "Time can feel longer or shorter depending on a person's perception. Relativity is truly both romantic and melancholic. - Steins;Gate" },
    { cn: "笛卡尔说过，无法下决定的人，要么是欲望太大，要么是悟性不足。", source: "心理测量者", en: "Descartes once said, those who cannot make decisions either have too much desire or lack understanding. - Psycho-Pass" },
    { cn: "爱的反面不是恨，而是无视。如果不感兴趣的话，就不会故意去杀害或者伤害对方。", source: "心理测量者", en: "The opposite of love is not hate, but indifference. If you're not interested, you wouldn't intentionally kill or hurt someone. - Psycho-Pass" },
    { cn: "人类可以通过内心的阴暗面，正视到隐藏在内心的残暴性，从而能培养出制约它们的良知、理性和善意。", source: "《心理测量者》", en: "Humans can face the hidden brutality in their hearts through their inner darkness, thereby cultivating conscience, reason, and kindness to restrain them. - Psycho-Pass" },
    { cn: "明明是既无法制裁恶人，也不能保护良民的法律，为什么你还要如此维护这样的法律呢？不是法律去保护人，而是人去遵守法律。古往今来，憎恨罪恶，谋求人生正道的人们的心意，积累起来变成了今天的法律，法律不是条款也不是系统，而是每个人心中都有的脆弱而不可替代的心意，相比愤怒与憎恨，这种心意总是脆弱得不堪一击。所以，为了不让力求创造更好世界的故人们的祈愿化为泡影，我必须坚持维护到底，绝不能放弃！", source: "心理测量者", en: "Why do you uphold a law that neither punishes the wicked nor protects the innocent? It's not the law that protects people, but people who abide by the law. Throughout history, the desire of those who hated evil and sought a righteous life has accumulated into today's laws. Laws are not rules or systems, but the fragile and irreplaceable intentions in everyone's hearts. Compared to anger and hatred, this intention is always vulnerable. So, to prevent the wishes of those who strove to create a better world from being in vain, I must uphold it to the end and never give up! - Psycho-Pass" },
    { cn: "仅仅是无视并且否认超越理解范畴的东西，总有一天会让自己后悔的，接受眼前发生的事实，那正是一个人成长的捷径，小姑娘。", source: "心理测量者", en: "Simply ignoring and denying things beyond your understanding will one day make you regret it. Accepting the facts in front of you is the shortcut to growth, young lady. - Psycho-Pass" },
    { cn: "当你注视着黑暗的时候,黑暗也在注视着你。", source: "心理测量者", en: "When you gaze into the darkness, the darkness also gazes into you. - Psycho-Pass" },
    { cn: "我只要活着就好。", source: "心理测量者", en: "As long as I'm alive, that's enough. - Psycho-Pass" },
    { cn: "人类无法忍受孤独，所以创造了神。", source: "心理测量者", en: "Humans cannot bear solitude, so they created God. - Psycho-Pass" },
    { cn: "即使想哭泣的时候也必须忍住，因为，等待我的不是幸福的未来，而是更深的绝望，所以我没有时间流泪。", source: "心理测量者", en: "Even when I want to cry, I must hold back. Because what awaits me is not a happy future, but deeper despair, so I have no time to cry. - Psycho-Pass" },
    { cn: "人生就是不停地做选择，改变自己的选择，推翻原来的决定，不断地反复。", source: "心理测量者", en: "Life is about making choices, changing your choices, overturning your decisions, and repeating the process. - Psycho-Pass" },
    { cn: "正因为是你，所以才会有意义。", source: "心理测量者", en: "It has meaning precisely because it's you. - Psycho-Pass" }


];
    


function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

function displayQuote() {
    const quote = getRandomQuote();
    document.querySelector('.anime-quote-cn').innerText = `${quote.cn} - ${quote.source}`;
    document.querySelector('.anime-quote-en').innerText = `${quote.en}`;
}

window.onload = function() {
    displayQuote();
};